name: visdrone
root: ${VISDRONE_ROOT:-../../data/VisDrone}
num_classes: 10
classes:
  - pedestrian
  - people
  - bicycle
  - car
  - van
  - truck
  - tricycle
  - awning-tricycle
  - bus
  - motor

splits:
  train:
    images: images/train
    annotations: annotations/train.json
  val:
    images: images/val
    annotations: annotations/val.json
  test:
    images: images/test
    annotations: annotations/test.json

adapters:
  esod: {}
  querydet:
    runner: visdrone
    short_length: "[1200]"
    max_length: 1999
  ceasc:
    dataset_type: CocoDataset
